# Defaults
sf.pollWaitMillis = 30000
sf.maxPoll = 200

# Number of components per retreive call
# This will be the default batch size for all metadata types unless
# there is a type specific batch size defined
#
sf.batchSize = 250

# Batch Sizes can be defined per Metadata Type to override
# default value set by sf.batchSize.
#
#
# Examples:
# sf.batchSize.CustomObjectTranslation = 50
# sf.batchSize.Report = 10

# Number of concurrent retreive calls
sf.concurrency = 4

# Use 'https://login.salesforce.com' for production or developer edition
# Use 'https://test.salesforce.com for sandbox.
# sf.serverurl = https://login.salesforce.com


# Comma seperated list of metadata types that should be excluded from retrieval
sf.excludeTypes =

# API version used for retrievals
sf.apiVersion=66.0
